// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent information returned to the development UI.
 *
 * This struct contains essential agent metadata including the ID,
 * which is not part of the A2A AgentCard specification.
 */
export type AgentInfo = { 
/**
 * Unique identifier for this agent
 */
id: string, 
/**
 * Human-readable agent name
 */
name: string, 
/**
 * Agent version string
 */
version: string, 
/**
 * Optional description of agent capabilities
 */
description?: string, 
/**
 * Number of skills registered with this agent
 */
skill_count: number, };
