// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StateTransition = { from_state: string | null, to_state: string, timestamp: string, trigger: string, };
