// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StateTransition } from "./StateTransition";

export type TaskTransitionsResponse = { transitions: Array<StateTransition>, };
